### PR TITLE
Jetty core Handler that wraps Spring HttpHandler as an adaptor

### PR DESCRIPTION
**Pull request by gregw**
Implement a Jetty core `Handler` that uses a spring `HttpHandler` without the overhead of servlets and using reactive async abstraction.

### CODE REVIEW

**Comment by lachlan-roberts** [comment]
@gregw you should be able to assign to me now

**Comment by gregw** [comment]
@lachlan-roberts see https://github.com/jetty/jetty.project/pull/11288, which contains a fix to the `Content.Sink.Subscriber` that you may need to make this work

**Comment by lachlan-roberts** [comment]
@gregw I have pushed the commits to implement the write side.
All tests inside `spring-web/src/test` are passing now.

**Comment by gregw** [comment]
@lachlan-roberts what was the conclusion about websocket upgrade?

**Comment by gregw** [comment]
I've opened draft https://github.com/spring-projects/spring-framework/pull/32097 to solicit more feedback

**Comment by gregw** [comment]
@lachlan-roberts unsurprisingly, we are failing websocket tests: org.springframework.web.reactive.socket.WebSocketIntegrationTests

**Comment by lachlan-roberts** [comment]
WebSocket tests are passing now.

There is a `WebSocketClient` with implementations from netty, tomcat and undertow.
So adding this to my TODO to write a Jetty implementation for this.

**Comment by gregw** [comment]
Closed in favor of https://github.com/spring-projects/spring-framework/pull/32097

**Pull request closed without merging**
